# Generated by Django 4.1.6 on 2023-02-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='course',
            field=models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('Full Stack', 'Full Stack'), ('C', 'C'), ('C++', 'C++'), ('Others', 'Others')], default='Others', max_length=30),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Enter Mail Id'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Enter Your Name'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.IntegerField(help_text='phone number must be in 10 digits', verbose_name='Enter Phone Number'),
        ),
    ]
