# Generated by Django 4.1.6 on 2023-02-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_enquiry_course_alter_enquiry_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdId', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('course', models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('C', 'C'), ('C++', 'C++'), ('Full Stack', 'Full Stack'), ('Others', 'Others')], max_length=20)),
                ('fees', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
